= Nguyen Thi Viet Ha - Project Portfolio
:toc:
:toc-title:
:toc-placement: preamble
:experimental:
:sectnums:
:imagesDir: ../images
:stylesDir: ../stylesheets


= PROJECT: Infinity Book
Welcome to my portfolio page for CS2103T AY 2017/2018 Sem 2 project - Infinity Book.

== Overview

include::../UserGuide.adoc[tag=introduction]

== Summary of contributions

*Code contributed*: [https://github.com/CS2103JAN2018-W11-B3/main/blob/master/collated/functional/deeheenguyen.md[Functional code]]
[https://github.com/CS2103JAN2018-W11-B3/main/blob/master/collated/test/deeheenguyen.md[Test code]]_

=== Major enhancement: added the interview management.
** Motivation: Interviewing is one of the important steps in recruiting process.
HR may need a tool to manage interview efficiently.
** What it does: allows the user to add the interview relevant command which are add interview command,
find interview command, listing interview command.
** Highlights: This enhancement affects existing commands and commands to be added in future. It required an in-depth
analysis of design alternatives. The implementation too was challenging as it required changes to existing model, ui,
and storage.


=== Minor enhancement: added the view command.
** Motivation: The HR may want to find more details information of specific candidates.
The view command helps HR with this problem.
** What it does: allows user to view a specific person by email ID and display the linked page of the person.
** Highlights: This enhancement affects existing commands and commands to be added in future. It required an in-depth
 analysis of design alternatives. The implementation too was challenging as it required changes to existing commands.


=== Other contributions:

==== Project management:
* Managed releases `v1.5rc` on GitHub
* Managed milestones on GitHub.

==== Enhancements to existing features:
* Updated the add command to support viewing a person (Pull requests
https://github.com/CS2103JAN2018-W11-B3/main/pull/15[#15])
* Wrote additional tests for existing features to increase coverage (Pull requests
https://github.com/CS2103JAN2018-W11-B3/main/pull/168[#168],
https://github.com/CS2103JAN2018-W11-B3/main/pull/166[#166])

==== Documentation:
*** Did cosmetic tweaks to existing contents of the User Guide: https://github.com[#14]
** Community:
*** PRs reviewed (with non-trivial review comments): https://github.com/CS2103JAN2018-W11-B3/main/pull/51[#51]
*** Reported bugs and suggestions for other teams in the class


== Contributions to the User Guide
include::../UserGuide.adoc[tag=viewcommand]

include::../UserGuide.adoc[tag=interviewmanagement]

== Contributions to the Developer Guide
include::../DeveloperGuide.adoc[tag=viewcommand]

include::../DeveloperGuide.adoc[tag=interviewmanagement]

